<h6 class="card-title question-pre">Python: code. exceptions
# create a skeletal try catch exceptions template 


# try to get user input
# create except for ValueError and ZeroDivisionError


# raise an Exception


# raise an Exception and try cath it


# create a DogNotFoundException class and use it as raise Exception


# create a normal function and raise an Exception inside
# call the function in try catch


</h6>
<p class="card-text answer-pre">
# create a skeletal try catch exceptions template 
try:
    # some lines of code
except <ERROR1>:
    # handler <ERROR1>
except <ERROR2>:
    # handler <ERROR2>
except:
else:
finally:

# try to get user input
# create except for ValueError and ZeroDivisionError
try:
    age = int(input('Age: '))
    print(age)
except ValueError as ex:
    print("You didn't enter a valid age.")
    print(ex)
    print(type(ex))
except ZeroDivisionError:
    print('Age cannot be 0')
else:
    print("No exceptions were thrown")

# raise an Exception
raise Exception('An error!')

# raise an Exception and try cath it
try:
    raise Exception('An Error!')
except Exception as error:
    print(error)

# create a DogNotFoundException class and use it as raise Exception
class DogNotFoundException(Exception): # DogNotFoundException using inheritance
    pass
try:
    raise DogNotFoundException()
except DogNotFoundException:
    print('Dog not found!')	

# create a normal function and raise an Exception inside
# call the function in try catch
def calculate_xfactor(age):
    if age <= 0:
        raise ValueError("Age cannot be 0 or less") 
    return 10 / age
try:
    calculate_xfactor(-1)
except ValueError as error:
    print(error)    
</p>